### ISSUE TITLE
Issue starting the example

### ISSUE THREAD

**Issue by whatisgravity** [r-medina/gmaj#3]
I'm trying to dissect different DHT examples to learn more about distributed systems. I was trying to use your example and got the following error:

    cannot use _Node_GetPredecessor_Handler (type func(interface {}, context.Context, grpc.Codec, []byte) (interface {}, error)) as type grpc.methodHandler in field value

Have you ran into this issue before?

**Comment by asubiotto** [comment]
We're looking into it, thanks!

**Comment by whatisgravity** [comment]
I can provide the full error if you are not able to reproduce it, there were more errors. 

Thank you for writing very clear code, this has made it a lot easier to understand the finger tables.

**Comment by asubiotto** [comment]
I was able to reproduce it. The problem seems to be that a new version of grpc broke our code. Working on getting this fixed. Sorry for the delay!
